Repository TeskaLabs/asab, pull requests merged in 2023-05, with the labels that each got.

#395 New auth service and decorators
  asab/api/doc.py
  asab/api/log.py
  asab/api/web_handler.py
  asab/exceptions.py
  asab/metrics/web_handler.py
  asab/web/auth/__init__.py
  asab/web/auth/decorator.py
  asab/web/auth/service.py
  asab/web/authz/__init__.py
  asab/web/authz/decorator.py
  asab/web/authz/middleware.py
  asab/web/authz/service.py
  asab/web/rest/json.py
  asab/web/tenant/midleware.py
  examples/web-auth.py
Labels: enhancement, breaking change

#408 Fix issue with proactor using event loop.
  asab/library/providers/zookeeper.py
Labels: bug

#409 return True when resources are ok
  asab/web/auth/service.py
Labels: bug

#417 Reload auth public keys when needed
  asab/web/auth/service.py
Labels: enhancement

#420 Add an application-level restart
  asab/application.py
Labels: enhancement

#419 Add an explicit exception handling to PubSub synchronous message delivery
  asab/pubsub.py
Labels: bug
