Repository TeskaLabs/asab, pull requests merged in 2023-07, with the labels that each got.

#444 Extend the TLS opts on providing CA certificate.
  asab/tls.py
Labels: enhancement

#445 Unit tests for crash control
  test/__init__.py
  test/test_crash/__init__.py
  test/test_crash/app_crash_01.py
  test/test_crash/app_crash_02.py
  test/test_crash/app_crash_03.py
  test/test_crash/test_crash.py
Labels: unit tests

#441 Add API Key authorization option for ElasticSearch
  asab/storage/elasticsearch.py
  asab/tls.py
  examples/storage_elasticsearch.py
Labels: enhancement

#452 Documentation: docstrings in `asab.Application`
  asab/application.py
  docs/reference/application/application.md
Labels: documentation

#448 Bug: Multiple items with same name from different providers
  asab/library/providers/abc.py
  asab/library/providers/azurestorage.py
  asab/library/providers/filesystem.py
  asab/library/providers/git.py
  asab/library/providers/zookeeper.py
  asab/library/service.py
Labels: bug
