Repository TeskaLabs/asab, pull requests merged in 2023-03, with the labels that each got.

#356 Defect: Zookeeper sometimes has forward slash at the end of path.
  asab/library/providers/zookeeper.py
Labels: bug, breaking change

#355 Improved docker detection.
  asab/application.py
  asab/docker/__init__.py
Labels: bug

#359 Zookeeper integration refactored.
  asab/library/providers/zookeeper.py
  asab/zookeeper/container.py
  asab/zookeeper/service.py
  asab/zookeeper/wrapper.py
  doc/asab/zookeeper.rst
  doc/index.rst
Labels: enhancement, breaking change

#362 ASAB library path fixes + subscribe() is now async call
  asab/api/service.py
  asab/library/providers/abc.py
  asab/library/providers/filesystem.py
  asab/library/providers/git.py
  asab/library/service.py
  asab/zookeeper/container.py
  asab/zookeeper/service.py
Labels: bug

#361 Feature: now colors are disabled when running in container
  asab/log.py
Labels: enhancement

#371 Feature/Optional argument `event_type` added into `Upsertor.execute()` method
  asab/storage/elasticsearch.py
  asab/storage/inmemory.py
  asab/storage/mongodb.py
  asab/storage/upsertor.py
Labels: enhancement

#374 Remove obsolete authn module
  asab/web/authn/__init__.py
  asab/web/authn/basicauth.py
  asab/web/authn/middleware.py
  asab/web/authn/oauth/__init__.py
  asab/web/authn/oauth/forwarder.py
  asab/web/authn/oauth/method.py
  asab/web/authn/oauth/middleware.py
  asab/web/authn/oauth/service.py
  asab/web/authn/pubkeyauth.py
  doc/TODO.md
  doc/asab/web/authn.rst
  examples/web-authn-oauth.py
  examples/web-authn-pubkey.py
Labels: breaking change

#358 Metrics: Feature/correct timestamp
  asab/metrics/http.py
  asab/metrics/influxdb.py
  asab/metrics/metrics.py
  asab/metrics/web_handler.py
  test/test_metrics/baseclass.py
  test/test_metrics/test_agg_counter.py
  test/test_metrics/test_counter.py
  test/test_metrics/test_duty_cycle.py
  test/test_metrics/test_eps_counter.py
  test/test_metrics/test_histogram.py
  test/test_metrics/test_validation.py
Labels: enhancement

#379 Documentation/asab storage
  asab/library/service.py
  asab/storage/elasticsearch.py
  asab/storage/inmemory.py
  asab/storage/mongodb.py
  asab/storage/service.py
  asab/storage/upsertor.py
  doc/asab/storage.rst
  doc/conf.py
  doc/index.rst
  examples/mongodb_storage.py
  examples/storage_elasticsearch.py
  examples/storage_inmemory.py
  examples/storage_mongodb.py
Labels: enhancement
