Repository TeskaLabs/asab, pull requests merged in 2023-06, with the labels that each got.

#430 Verbose dev mode info when the app starts
  asab/web/auth/service.py
  examples/web-auth.py
Labels: enhancement

#415 Change detection in the library zookeeper provider
  asab/library/providers/zookeeper.py
  examples/library-subscribe.py
Labels: enhancement

#436 Fix auth for handlers with multiple decorators
  asab/api/doc.py
  asab/web/auth/service.py
  asab/web/rest/json.py
  examples/web-auth.py
Labels: bug

#439 Optionally run housekeeping at startup
  asab/application.py
  asab/config.py
Labels: enhancement

#407 Enhancement : Add library level info to list
  asab/library/item.py
  asab/library/providers/abc.py
  asab/library/providers/filesystem.py
  asab/library/providers/zookeeper.py
  asab/library/service.py
Labels: enhancement, breaking change
