Repository TeskaLabs/asab, pull requests merged in 2023-12, with the labels that each got.

#527 Fix of the incorrect "set_ready" propagation in libsreg.
  asab/library/providers/libsreg.py
Labels: bug

#517 Better exception handling in PubSub
  asab/pubsub.py
Labels: enhancement

#516 Task service emits PubSub message when a task is finished.
  asab/task.py
Labels: enhancement

#534 Improved error handing of metrics propagation into InfluxDB.
  asab/metrics/influxdb.py
Labels: enhancement

#531 Library documentation improvements
  asab/library/item.py
  asab/library/service.py
  docs/images/library/asab-library-layers.drawio.png
  docs/images/library/asab-library.drawio.png
  docs/reference/library.md
  docs/reference/services/alert.md
  docs/reference/services/index.md
  docs/reference/services/library.md
  docs/reference/services/metrics/built_ins.md
  docs/reference/services/metrics/create_metrics.md
  docs/reference/services/metrics/index.md
  docs/reference/services/metrics/interpretation.md
  docs/reference/services/metrics/metrics_types.md
  docs/reference/services/metrics/monitoring.md
  docs/reference/services/metrics/tags.md
  docs/reference/services/proactor.md
  docs/reference/services/sentry.md
  docs/reference/services/storage.md
  docs/reference/services/task.md
  docs/reference/services/web/authorization_multitenancy.md
  docs/reference/services/web/cors.md
  docs/reference/services/web/rest_api_docs.md
  docs/reference/services/web/tls.md
  docs/reference/services/web/web-server.md
  docs/reference/services/zookeeper.md
  mkdocs.yml
Labels: documentation

#541 Small but important fixes
  asab/api/discovery.py
  asab/library/providers/git.py
  asab/metrics/influxdb.py
Labels: bug
