Repository TeskaLabs/asab, pull requests merged in 2023-08, with the labels that each got.

#463 REST API Documentation
  docs/images/rest-api-docs/1-preview.png
  docs/images/rest-api-docs/2-preview-with-docs.png
  docs/images/rest-api-docs/3-authorization.png
  docs/images/rest-api-docs/4-module.png
  docs/images/rest-api-docs/5-class.png
  docs/reference/web/rest_api_docs.md
  mkdocs.yml
Labels: documentation

#465 Rename ConfigObject to Configurable
  asab/__init__.py
  asab/alert.py
  asab/config.py
  asab/metrics/http.py
  asab/metrics/influxdb.py
  asab/tls.py
  asab/web/container.py
  asab/zookeeper/container.py
Labels: enhancement

#461 Documentation for LibraryService
  asab/library/service.py
Labels: documentation

#467 WIP: Documentation for `PubSub`
  asab/pubsub.py
  docs/reference/pubsub/reference.md
  mkdocs.yml
Labels: documentation

#468 Add `getmultiline` method
  asab/config.py
  examples/config_getmultiline.py
Labels: enhancement

#470 Documentation: integration
  .gitlab-ci.yml
  mkdocs.yml
Labels: documentation

#466 Add config switch to disable auth
  asab/web/auth/service.py
  examples/web-auth.py
Labels: enhancement

#472 Documentation: Proofreading the Application section
  asab/application.py
  docs/reference/application/reference.md
  docs/reference/modules_services/reference.md
  mkdocs.yml
Labels: documentation

#473 Documentation: proofreading and small fixes
  asab/application.py
  docs/reference/application/reference.md
  docs/reference/modules_services/reference.md
  docs/reference/storage/reference.md
Labels: documentation

#475 Rename TLS password config option to avoid name conflicts
  asab/tls.py
Labels: enhancement, breaking change

#478 Fix of the syslog handling when the socket is not yet ready.
  asab/log.py
Labels: bug

#484 Change file tree structure of Documentation
  docs/reference/alert.md
  docs/reference/application.md
  docs/reference/configuration.md
  docs/reference/library.md
  docs/reference/logging.md
  docs/reference/modules_services.md
  docs/reference/pubsub.md
  docs/reference/storage.md
  docs/reference/zookeeper.md
  mkdocs.yml
Labels: documentation

#480 Dump logs to stderr when syslog write fails
  asab/log.py
Labels: bug

#489 Fix dev userinfo validation
  asab/web/auth/service.py
Labels: bug

#487 Fix: Metrics must be sent even when tag is None
  asab/metrics/influxdb.py
Labels: bug

#493 Add '--no-auth' argument
  asab/application.py
  asab/web/auth/service.py
Labels: enhancement

#483 Configurable OpenAPI server URL
  asab/api/doc.py
Labels: enhancement

#481 ASAB Library: Allow set in `.disabled.yaml`
  asab/library/service.py
Labels: bug

#492 Merge `enabled` and `dev_mode` config switch
  asab/application.py
  asab/web/auth/service.py
  docs/reference/web/authorization_multitenancy.md
  examples/web-auth.py
Labels: enhancement, breaking change
