Repository TeskaLabs/asab, pull requests merged in 2024-11, with the labels that each got.

#632 Introduce tenant providers in TenantService
  asab/web/tenant/providers/__init__.py
  asab/web/tenant/providers/abc.py
  asab/web/tenant/providers/static.py
  asab/web/tenant/providers/web.py
  asab/web/tenant/service.py
Labels: enhancement

#635 Restore AuthService.get_authorized_tenant as a legacy method
  asab/web/auth/service.py
Labels: bug

#637 Deprecate X-Tenant header
  asab/api/discovery.py
  asab/web/auth/service.py
Labels: bug

#641 Revise Authorization attributes
  asab/web/auth/authorization.py
Labels: enhancement

#633 Tenant extraction in TenantService
  asab/web/auth/authorization.py
  asab/web/auth/decorator.py
  asab/web/auth/service.py
  asab/web/tenant/__init__.py
  asab/web/tenant/decorator.py
  asab/web/tenant/midleware.py
  asab/web/tenant/service.py
  asab/web/tenant/utils.py
  asab/web/tenant/web.py
  docs/reference/services/web/authorization.md
  docs/reference/services/web/multitenancy.md
  examples/web-auth.py
Labels: enhancement

#643 Fix docs paths
  mkdocs.yml
Labels: bug, documentation

#640 LibraryService Documentation: Tenant in contextvar
  asab/library/service.py
Labels: documentation

#644 Add support for Python 3.12 and 3.13
  .github/workflows/ci.yaml
  setup.py
Labels: enhancement
