Repository TeskaLabs/asab, pull requests merged in 2024-01, with the labels that each got.

#540 Library find function
  asab/library/providers/filesystem.py
  asab/library/providers/zookeeper.py
  asab/library/service.py
Labels: enhancement

#545 Sentry documentation improvements
  docs/reference/services/sentry.md
Labels: documentation

#512 Improve on the Swagger doc
  asab/api/doc.py
  asab/api/doc_templates.py
  asab/web/__init__.py
  examples/webserver.py
Labels: enhancement, good first issue
