Repository TeskaLabs/asab, pull requests merged in 2024-04, with the labels that each got.

#565 Updates documentation: new config option for Storage
  docs/reference/services/storage.md
Labels: documentation

#569 Fix OpenAPI specs to compile without errors
  asab/api/doc.py
Labels: bug

#570 Get OpenAPI route tag form class docstring
  asab/api/doc.py
  asab/api/doc_templates.py
Labels: enhancement
