Repository TeskaLabs/asab, pull requests merged in 2024-12, with the labels that each got.

#647 Remove auth exception for HEAD requests
  asab/web/auth/service.py
Labels: bug

#649 Fix the interaction of auth and tenant modules
  asab/config.py
  asab/web/auth/service.py
  asab/web/tenant/providers/static.py
  asab/web/tenant/providers/web.py
  asab/web/tenant/service.py
  asab/web/tenant/utils.py
  examples/web-auth.py
Labels: bug

#650 ASAB API must require no tenant
  asab/api/doc.py
  asab/api/log.py
  asab/api/web_handler.py
  asab/metrics/web_handler.py
Labels: bug

#654 Disallow using `tenant` parameter in path and query at the same time
  asab/web/tenant/utils.py
Labels: enhancement

#656 Auth unit tests
  asab/web/auth/authorization.py
  asab/web/auth/service.py
  test/__init__.py
  test/test_auth/__init__.py
  test/test_auth/test_access_control.py
  test/test_auth/test_authorization.py
Labels: enhancement

#657 Document public authorization attributes
  asab/web/auth/authorization.py
Labels: documentation

#658 Swagger: Fix duplicate path parameters
  asab/api/doc.py
  asab/api/log.py
  asab/api/web_handler.py
Labels: bug
