Repository TeskaLabs/asab, pull requests merged in 2024-08, with the labels that each got.

#593 Repair items encrypted with broken padding method
  asab/storage/mongodb.py
  asab/storage/service.py
Labels: bug

#533 Create Service Discovery docs
  asab/api/discovery.py
  docs/reference/services/service-discovery.md
  docs/reference/services/zookeeper.md
  mkdocs.yml
Labels: documentation

#585 Internal authorization via discovery service
  asab/api/discovery.py
  asab/web/auth/service.py
  examples/internal-auth.py
Labels: enhancement

#598 JSON serializer can handle dataclasses + better exception handling in threadsafe PubSub
  asab/pubsub.py
  asab/web/rest/json.py
Labels: enhancement
