Repository TeskaLabs/asab, pull requests merged in 2025-01, with the labels that each got.

#662 Mongo storage: If the object is new (version is 1), set the _c date to now
  asab/storage/mongodb.py
Labels: bug

#663 ZooKeeper `upsert()` prioritizes `set()` before `create()`
  asab/zookeeper/wrapper.py
Labels: enhancement

#652 Tenants ready status and updating
  asab/web/tenant/decorator.py
  asab/web/tenant/providers/abc.py
  asab/web/tenant/providers/static.py
  asab/web/tenant/providers/web.py
  asab/web/tenant/service.py
  asab/web/tenant/utils.py
Labels: enhancement

#664 Protect ASAB API
  asab/api/log.py
  asab/api/web_handler.py
  asab/metrics/web_handler.py
  asab/web/auth/__init__.py
  asab/web/auth/decorator.py
Labels: enhancement

#666 Satanic documentation fixes in auth and tenant hell
  asab/web/auth/authorization.py
  asab/web/auth/decorator.py
  asab/web/tenant/service.py
  docs/reference/services/web/authorization.md
  docs/reference/services/web/multitenancy.md
Labels: documentation
